config/routes.rb
Depot::Application.routes.draw do
  get "admin" => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"
  resources :products do
    get :who_bought, on: :member
  end

  root 'store#index', as: 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Pragprog Books Online Store</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>



</head>
<body class="<%= controller.controller_name %>">
	<div id="banner">
		<%= image_tag("logo.png") %>
		<%= @page_title || "Pragmatic Bookshelf" %>
	</div>
	<div id="columns">
		<div id="side">

			<%if @cart  %>

				<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
				 	<%= render @cart %> 
				 <% end %>
			<% end %>

			 <ul>
				<li><a href="http://www....">Home</a></li>
				<li><a href="http://www..../faq">Questions</a></li> <li><a href="http://www..../news">News</a></li>
				<li><a href="http://www..../contact">Contact</a></li>
			</ul>

			<% if session[:user_id] %>
				<ul>
					<li><%= link_to 'orders', orders_path %></li>
				    <li><%= link_to 'rders', products_path %></li>
				    <li><%= link_to 'Orders', users_path %></li>
				 </ul>
				 <%= button_to 'logout', logout_path, method: :delete %>
			<% end %>


		 </div>
		<div id="main"> 
			<%= yield %>
		</div>
	</div>
</body>
</html>

</body>
</html>